/**:
  ros__parameters:
    costmap_topic: local_costmap/costmap_raw
    footprint_topic: local_costmap/published_footprint
    # 🚀全向底盘修改：从5→10Hz（适应快速全向行为）
    # cycle_frequency: 5.0               
    cycle_frequency: 10.0
    # 🚀全向底盘新增横向避障行为               
    # behavior_plugins: ["spin", "backup", "drive_on_heading", "assisted_teleop", "wait"]
    behavior_plugins: ["spin", "backup", "drive_on_heading", "assisted_teleop", "wait", "lateral_escape"]
    lateral_escape:
      plugin: "nav2_behaviors/LateralEscape" # 自定义横向避障行为
      enabled: false                         # 可以先关闭直至开发完成（开发完后就立即打开）
      escape_velocity: 0.3                  # 横向逃逸速度
      escape_distance: 0.5                  # 横向移动距离

    spin:
      plugin: "nav2_behaviors/Spin"
      # 🚀全向底盘修改：降低旋转速度/加速度限制
      max_rotational_vel: 0.8               # 原1.0 → 更平缓旋转
      rotational_acc_lim: 2.0               # 原3.2 → 降低旋转加速度
      # 🚀新增横向补偿参数
      allow_lateral_adjustment: true        # 旋转时允许横向微调
      lateral_compensation_ratio: 0.3

    backup:
      plugin: "nav2_behaviors/BackUp"
      # 🚀全向底盘修改：允许Y轴方向避障后退
      backup_direction: [0.0, -1.0, 0.0]    # 原[-1.0,0.0,0.0] → Y轴反向
      backup_speed: 0.2                     # 原默认0.025
      backup_distance: 0.4   
    drive_on_heading:
      plugin: "nav2_behaviors/DriveOnHeading"
      # 🚀全向底盘修改：启用全向移动模式
      holonomic: true                       # 允许任意方向移动
      max_linear_vel: 0.3                   # 合速度上限（√(vx²+vy²)）
      max_linear_acc: 0.5                   # 线加速度限制
    wait:
      plugin: "nav2_behaviors/Wait"
    assisted_teleop:
      plugin: "nav2_behaviors/AssistedTeleop"
    global_frame: odom
    robot_base_frame: base_link
    transform_tolerance: 0.1
    use_sim_time: False
    simulate_ahead_time: 1.5     # 🚀从2.0→1.5（全向响应更快）
    # 🚀新增安全检测参数
    collision_checking_frequency: 5.0       # 碰撞检测频率提升
    safety_radius: 0.4                      # 安全半径（原默认0.3）

    # max_rotational_vel: 1.0
    # min_rotational_vel: 0.4
    # rotational_acc_lim: 3.2