/**:
  ros__parameters:
    use_sim_time: False
    smoothing_frequency: 20.0
    scale_velocities: False
    feedback: "OPEN_LOOP"
    # 🚀全向底盘修改：启用Y轴运动参数
    max_velocity: [0.2, 0.2, 1.0]       # 原[0.1,0.0,1.0] → X/Y/θ速度上限
    min_velocity: [-0.2, -0.2, -1.0]     # 原[-0.1,0.0,-1.0] → 允许反向横向移动
    # 🚀全向底盘修改：设置Y轴加速度
    max_accel: [2.5, 0.5, 3.2]          # 原[2.5,0.0,3.2] → X/Y/θ加速度
    max_decel: [-2.5, -0.5, -3.2]        # 原[-2.5,0.0,-3.2] → X/Y/θ减速度
    odom_topic: "odom"
    odom_duration: 0.1
    # 🚀全向底盘修改：设置横向运动死区（根据硬件噪声调整）
    deadband_velocity: [0.01, 0.01, 0.01]    # 原[0,0,0] → 避免微小速度抖动 
    velocity_timeout: 1.0



# /**:
#   ros__parameters:
#     feedback: "CLOSED_LOOP"                 # 🚀改为闭环模式
#     enable_odometry_tracking: true          # 启用里程计跟踪
#     odom_topic: "odom"                      # 确保与真实里程计话题一致
#     odom_duration: 0.05                     # 缩短至50ms（要求高频里程计）
#     # 动态调节参数
#     velocity_feedback_factor: 0.9           # 反馈增益（0~1）
#     use_velocity_feedback: true             # 启用速度闭环
#     use_position_feedback: false            # 根据需求选择是否启用位置闭环