/**:
  ros__parameters:
    use_sim_time: False
    # 🚀全向底盘修改：建议提升到 50（适应更高频的全向微调）
    # loop_rate: 20            
    loop_rate: 50            
    stop_on_failure: false
    waypoint_task_executor_plugin: "wait_at_waypoint"
    # 🚀全向底盘修改：添加转向插件（适应全向路径点的任意朝向）
    waypoint_task_executor_plugins: ["wait_at_waypoint", "spin_at_waypoint"]
    spin_at_waypoint:
      plugin: "nav2_waypoint_follower::SpinAtWaypoint"
      enabled: True
      spin_frequency: 0.5                 # 旋转速度（Hz）
      target_yaw: 0.0                     # 目标朝向（可动态设置）

    wait_at_waypoint:
      plugin: "nav2_waypoint_follower::WaitAtWaypoint"
      enabled: True
      # 🚀全向底盘修改：从5000ms→2000ms（减少停顿时间）
      # waypoint_pause_duration: 5000
      waypoint_pause_duration: 2000

      # 🚀新增全向容差参数
      positional_tolerance: 0.15          # X/Y位置容差（原默认0.25）
      angular_tolerance: 0.5              # 朝向容差（弧度）
      
    # 🚀全向底盘新增全局路径参数
    global_path_updates: True             # 允许动态更新全局路径
    use_holonomic_paths: True             # 启用全向路径支持
